services:
  mangarr:
    image: ghcr.io/mangarrteam/mangarr:latest
    container_name: mangarr
    ports:
      - "80:80"
    volumes:
      - ${PROJECT_ROOT}:/app/project_root
      - ${MANGA_FOLDER}:/manga/media
    restart: unless-stopped
