# Generated by Django 5.2.7 on 2025-10-08 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('database_manga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_edit', to='database_manga.chapter', verbose_name='processes.models.edit_chapter.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='MonitorChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plugin', models.CharField(verbose_name='processes.models.process_base.plugin')),
                ('url', models.URLField(unique=True, verbose_name='processes.models.process_base.url')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='processes.models.process_base.last_run')),
                ('arguments', models.JSONField(blank=True, default=dict, verbose_name='processes.models.process_base.arguments')),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_manga.manga', verbose_name='processes.models.monitor_chapter.manga')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MonitorManga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plugin', models.CharField(verbose_name='processes.models.process_base.plugin')),
                ('url', models.URLField(unique=True, verbose_name='processes.models.process_base.url')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='processes.models.process_base.last_run')),
                ('arguments', models.JSONField(blank=True, default=dict, verbose_name='processes.models.process_base.arguments')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_manga.library', verbose_name='database.models.manga_monitor.library')),
                ('manga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database_manga.manga', verbose_name='processes.models.monitor_manga.manga')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
