# Generated by Django 5.2.7 on 2025-10-18 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_manga', '0001_initial'),
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorchapter',
            name='manga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database_manga.manga', verbose_name='processes.models.monitor.manga'),
        ),
        migrations.AlterField(
            model_name='monitormanga',
            name='manga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database_manga.manga', verbose_name='processes.models.monitor.manga'),
        ),
    ]
