# Generated by Django 5.2.7 on 2025-10-08 00:08

import database.manga.lockable_fields
import django.db.models.deletion
import pathlib
import plugins.base
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Library', max_length=64, unique=True, verbose_name='database.models.library.name')),
                ('folder', models.CharField(default=pathlib.PureWindowsPath('D:/Nextcloud/Visual Studio/VS Code/Projects/Mangarr/V0.3/manga/media'), max_length=512, verbose_name='database.models.library.folder_path')),
                ('default', models.BooleanField(default=False, verbose_name='database.models.library.default')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plugin', models.CharField(choices=[], max_length=64, verbose_name='database.models.manga.plugin')),
                ('name', database.manga.lockable_fields.LockableCharField(verbose_name='database.models.manga.name')),
                ('localized_name', database.manga.lockable_fields.LockableCharField(verbose_name='database.models.manga.localized_name')),
                ('description', database.manga.lockable_fields.LockableCharField(verbose_name='database.models.manga.description')),
                ('genres', database.manga.lockable_fields.LockableListField(verbose_name='database.models.manga.genres')),
                ('tags', database.manga.lockable_fields.LockableListField(verbose_name='database.models.manga.tags')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='database.models.manga.date_added')),
                ('last_update', models.DateTimeField(auto_now_add=True, verbose_name='database.models.manga.last_update')),
                ('complete', database.manga.lockable_fields.LockableBoolField(verbose_name='database.models.manga.complete')),
                ('url', models.URLField(unique=True, verbose_name='database.models.manga.url')),
                ('file_folder', models.CharField(default=pathlib.PureWindowsPath('D:/Nextcloud/Visual Studio/VS Code/Projects/Mangarr/V0.3/manga/media'), max_length=512, verbose_name='database.models.manga.folder_path')),
                ('arguments', models.JSONField(blank=True, default=dict, verbose_name='processes.models.manga.arguments')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_manga.library', verbose_name='database.models.manga.library')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MangaANLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alternative_name', database.manga.lockable_fields.LockableCharField(verbose_name='database.models.manga.alternative_name')),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternative_names', to='database_manga.manga')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MangaRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plugin', models.CharField(choices=[], max_length=64, verbose_name='database.models.manga_request.plugin')),
                ('variables', models.JSONField(blank=True, default=dict, verbose_name='database.models.manga_request.variables')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_manga.library', verbose_name='database.models.manga_request.library')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='database.models.manga_request.requested_by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', database.manga.lockable_fields.LockableCharField(verbose_name='database.models.volume.name')),
                ('description', database.manga.lockable_fields.LockableCharField(verbose_name='database.models.volume.description')),
                ('number', database.manga.lockable_fields.LockableFloatField(verbose_name='database.models.volume.number')),
                ('arguments', models.JSONField(blank=True, default=dict, verbose_name='processes.models.volume.arguments')),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='database_manga.manga', verbose_name='processes.models.volume.manga')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', database.manga.lockable_fields.LockableCharField(verbose_name='database.models.chapter.name')),
                ('description', database.manga.lockable_fields.LockableCharField(verbose_name='database.models.chapter.description')),
                ('localization', database.manga.lockable_fields.LockableCharField(verbose_name='database.models.chapter.localization')),
                ('publisher', database.manga.lockable_fields.LockableListField(verbose_name='database.models.chapter.publisher')),
                ('imprint', database.manga.lockable_fields.LockableListField(verbose_name='database.models.chapter.imprint')),
                ('release_date', database.manga.lockable_fields.LockableDateTimeField(verbose_name='database.models.chapter.release_date')),
                ('writer', database.manga.lockable_fields.LockableListField(verbose_name='database.models.chapter.writer')),
                ('penciller', database.manga.lockable_fields.LockableListField(verbose_name='database.models.chapter.penciller')),
                ('inker', database.manga.lockable_fields.LockableListField(verbose_name='database.models.chapter.inker')),
                ('colorist', database.manga.lockable_fields.LockableListField(verbose_name='database.models.chapter.colorist')),
                ('letterer', database.manga.lockable_fields.LockableListField(verbose_name='database.models.chapter.letterer')),
                ('cover_artist', database.manga.lockable_fields.LockableListField(verbose_name='database.models.chapter.cover_artist')),
                ('editor', database.manga.lockable_fields.LockableListField(verbose_name='database.models.chapter.editor')),
                ('translator', database.manga.lockable_fields.LockableListField(verbose_name='database.models.chapter.translator')),
                ('page_count', database.manga.lockable_fields.LockableIntegerField(verbose_name='database.models.chapter.page_count')),
                ('format', database.manga.lockable_fields.LockableEnumField(enum_class=plugins.base.Formats, verbose_name='database.models.chapter.format')),
                ('age_rating', database.manga.lockable_fields.LockableEnumField(enum_class=plugins.base.AgeRating, verbose_name='database.models.chapter.age_rating')),
                ('isbn', database.manga.lockable_fields.LockableCharField(verbose_name='database.models.chapter.isbn')),
                ('number', database.manga.lockable_fields.LockableFloatField(verbose_name='database.models.chapter.number')),
                ('file', models.CharField(default=pathlib.PureWindowsPath('D:/Nextcloud/Visual Studio/VS Code/Projects/Mangarr/V0.3/manga/media'), max_length=512, verbose_name='database.models.chapter.file_path')),
                ('url', models.URLField(unique=True, verbose_name='database.models.chapter.url')),
                ('source_url', models.URLField(verbose_name='database.models.chapter.source_url')),
                ('downloaded', models.BooleanField(default=False, verbose_name='database.models.chapter.downloaded')),
                ('arguments', models.JSONField(blank=True, default=dict, verbose_name='processes.models.manga.arguments')),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='database_manga.volume', verbose_name='database.models.chapter.volume')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
