# Generated by Django 4.2.19 on 2025-05-15 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': [('can_restart', 'Can restart')]},
        ),
    ]
