# Generated by Django 4.2.19 on 2025-05-15 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_userprofile_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': [('can_restart', 'permission.can_restart')]},
        ),
    ]
