# Generated by Django 4.2.19 on 2025-05-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_registertoken_alter_userprofile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registertoken',
            name='token',
            field=models.CharField(editable=False, max_length=64, unique=True),
        ),
    ]
