# Generated by Django 4.2.19 on 2025-05-17 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_alter_registertoken_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': [('can_restart', 'permission.can_restart'), ('can_change_settings', 'permission.can_change_settings')]},
        ),
    ]
