# Generated by Django 4.2.19 on 2025-05-17 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': [('can_restart', 'permission.can_restart'), ('can_change_settings', 'permission.can_change_settings'), ('can_invite', 'permission.can_invite')]},
        ),
    ]
