# Generated by Django 4.2.19 on 2025-05-18 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_alter_userprofile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': [('can_restart', 'permission.can_restart'), ('can_change_settings', 'permission.can_change_settings'), ('can_invite', 'permission.can_invite'), ('can_manage_plugins', 'permission.can_manage_plugins')]},
        ),
    ]
