# Generated by Django 5.2.1 on 2025-05-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_alter_userprofile_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MangaRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plugin', models.CharField(choices=[('core_mangadex', 'MangaDex'), ('community_mangadex', 'MangaDex'), ('core_mangarr-test-plugin', 'Mangarr test plugin')], max_length=64, verbose_name='database.models.manga_request.plugin')),
                ('variables', models.JSONField(blank=True, default=dict, verbose_name='database.models.manga_request.variables')),
            ],
        ),
    ]
