# Generated by Django 5.2.1 on 2025-05-20 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_mangarequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mangarequest',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='database.models.manga_request.requested_by'),
        ),
        migrations.AlterField(
            model_name='mangarequest',
            name='plugin',
            field=models.CharField(choices=[('core_mangadex', 'MangaDex (core)'), ('community_mangadex', 'MangaDex (community)'), ('core_mangarr-test-plugin', 'Mangarr test plugin (core)')], max_length=64, verbose_name='database.models.manga_request.plugin'),
        ),
    ]
