# Generated by Django 5.2.1 on 2025-05-22 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(editable=False, max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_restart', 'permission.can_restart'), ('can_change_settings', 'permission.can_change_settings'), ('can_invite', 'permission.can_invite'), ('can_manage_plugins', 'permission.can_manage_plugins'), ('can_search', 'permission.can_search'), ('can_request', 'permission.can_request'), ('can_manage_requests', 'permission.can_manage_requests'), ('can_download', 'permission.can_download')],
            },
        ),
    ]
