# Generated by Django 5.2.7 on 2025-10-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_manga', '0001_initial'),
        ('database_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allowed_libraries',
            field=models.ManyToManyField(related_name='allowed_users', to='database_manga.library'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nsfw_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
