# Generated by Django 5.2.7 on 2025-10-08 00:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('database_manga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectorBase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectors', to='database_manga.library', verbose_name='database.models.library.name')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Connector',
                'verbose_name_plural': 'Connectors',
            },
        ),
        migrations.CreateModel(
            name='Kavita',
            fields=[
                ('connectorbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='connectors.connectorbase')),
                ('connector_library_id', models.CharField(max_length=32, unique=True, verbose_name='database.models.connector.kavita.library_id')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('connectors.connectorbase',),
        ),
    ]
